name: social_cv_client_dart_common
description: Shared Code between AngularDart and Flutter
version: 1.1.0

environment:
  sdk: '>=2.0.0-dev <3.0.0'

dependencies:
  meta: ^1.1.6

  # Web Client
  http : ^0.12.0
  dio : ^1.0.13

  # Rx
  async: ^2.0.8
  rxdart: ^0.20.0

  # Parsing
  json_annotation: ^2.0.0

dev_dependencies:
  build_runner: ^1.0.0
  json_serializable: ^2.0.0

authors:
  - Axel LE BOT <axellebot@gmail.com>